site_name: Wizeline MkDocs Template
nav:
  - Home: index.md
  - About: about.md
  - Academy Content: acaContent.md

theme:
  name: material
  palette:
    primary: black
    accent: indigo
  logo: images/wizeline_isotype.png

extra_css:
  - css/extra.css